### ISSUE TITLE
No footer displayed when using  GreaseMonkey / derivatives

### ISSUE THREAD

**Issue by HaloGeekster** [albert-sun/tamper-scripts#13]
The orange-red footer does not display when using popular userscript managers other than Tampermonkey. This prevents me from changing settings such as whitelist, blacklist, and auto refresh interval. Footer did not appear when testing with GreaseMonkey or ViolentMonkey, in either Chrome or Firefox.

I can currently work around this by copying the values generated from TamperMonkey's 'Storage' tab after changing the settings to ViolentMonkey's 'Values' tab.

For anyone else using ViolentMonkey that needs a quick work-around you can copy the settings below and paste them to Values -> All and edit them yo your heart's content. (just remember autoReloadInterval needs to be 10000 or higher to enable auto-refresh)

Default Values for settings:
```
 {
    "bestBuy-cartSavedItems_blacklistString": "[]",
    "bestBuy-cartSavedItems_whitelistString": "[\"3060\", \"3070\", \"3080\", \"3090\", \"6700\", \"6800\", \"6900\", \"5600X\", \"5800X\", \"5900X\", \"5950X\", \"PS5\"]",
    "bestBuy-cartSavedItems_initialClick": true,
    "bestBuy-cartSavedItems_reloadClicked": false,
    "bestBuy-cartSavedItems_autoReloadInterval": "0",
    "bestBuy-cartSavedItems_colorInterval": "250",
    "bestBuy-cartSavedItems_loadUnloadInterval": "50",
    "bestBuy-cartSavedItems_errorResetDelay": "250",
    "bestBuy-cartSavedItems_cartCheckDelay": "250",
    "bestBuy-cartSavedItems_cartSkipTimeout": "5000"
}
```

**Comment by cvocvo** [comment]
Even with TaperMonkey I'm not seeing the orange-red footer on whitelisted items.

**Comment by HaloGeekster** [comment]
The footer wont be on the items themselves, but rather at the bottom of the window when you are on the cart page.

As a side note I haven't messed around with it much to test different script managers out yet, but the auto-click to enter que didn't work on Violentmonkey in Firefox during yesterday's drop. Everything works perfectly if using Tampermonkey in Chrome, so for now I suggest using that.

**Comment by cvocvo** [comment]
Thanks for the quick reply; I see that red bar on the cart now. So to set this up we should just install it, increase the timeout, and then add some items to our saved items list and go to the cart? If they're in stock when the cart refreshes it will add them to the cart?
(not quite sure how to actually use this)

**Comment by HaloGeekster** [comment]
@cvocvo 
Baisic steps:
1. Add any items you are looking to get to your saved items.
2. Whenever BestBuy starts a drop open the cart page. All your saved items will populate with either Sold Out or Add to Cart buttons.
3. If it sees an Add to Cart button on a whitelisted product, the script will automaticaly click it. Some items (like GPUs) will then have the button trun grey and have an animated "Please Wait..." text. This means you have entered the que.
4. When your turn in que comes up the button will once again turn to a yellow Add to Cart button that the script will automatically click for you. (no need to refresh, it just happens)
5. From this point its in your own hands to rush through checkout as fast as you can.

Tips:
- **MOST IMPORTANTLY:** Refreshing the page will NOT take you out of que. You should still see "Please Wait..." on items that you are qued for after refreshing the page. However Items will not update from Waiting to Sold Out unless you refresh, so be sure to refresh occasionally to be up to date.
- You will also need to refresh to update previously Sold Out items to show their Add to Cart buttons as they become availible
- I recommend manual refreshing instead of the auto-refresh in the script, as it might try to refresh at an inopportune time
- The entire process can occur from the cart. The que for each product is tied to your browser, not tabs, so don't open any other tabs to the individual product pages. 
- If you get a "Not available for pickup from this location" message while checking out. You likely missed that chance to buy. Re-save the item and wait for more to become available.
