### ISSUE TITLE
Provide an indicator of recognized items

### ISSUE THREAD

**Issue by flarbear** [albert-sun/tamper-scripts#20]
It would be useful if the script would indicate how many (and which) items it recognizes in the Saved Item list so that we know that we've set up the filters correctly.

An indicator on the item itself would be ideal, but barring that, at least a list of the recognized items in the red/orange banner at the bottom, or its settings sheet, would be a good confirmation.

**Comment by albert-sun** [comment]
It currently shows what items are NOT being tracked in the logging window if that's good enough for you.

**Comment by flarbear** [comment]
Ah, I missed the logging window as I interpreted that icon (considered a "code" icon according to Google) as an icon to look at the script. Now that I know that it brings up a script log I can see the warnings there. Is there a reason that icon was chosen for the log?

**Comment by albert-sun** [comment]
It was originally meant to be a debug icon so that's what I went with, might change the icon to something more obvious.
