### ISSUE TITLE
TypeError: loggingFunction is not a function

### ISSUE THREAD

**Issue by hummerpj** [albert-sun/tamper-scripts#4]
I think you just have a typo in your `loadInterface()` function where you are not properly setting the `loggingFunction` global

**Comment by hummerpj** [comment]
Looks like this is fixed in a different branch (other than `main`).  Disregard

**Comment by albert-sun** [comment]
Yeah, I only pull to main for major updates so it doesn't get cluttered with pull requests. I'll try and make the heading bigger to NOT download from the main branch.
